// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlHl9933p34pfhLaa-sfUVCTjxDnQwMvk',
    appId: '1:703227333311:web:86a120dda4a86ea2e7940a',
    messagingSenderId: '703227333311',
    projectId: 'b2b-sales-master-app',
    authDomain: 'b2b-sales-master-app.firebaseapp.com',
    storageBucket: 'b2b-sales-master-app.firebasestorage.app',
    measurementId: 'G-4NY5Z0713G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnXlo0jGh_j0mo-7EgLdAj3BI-CjckNmU',
    appId: '1:703227333311:android:edebaeb506465dd9e7940a',
    messagingSenderId: '703227333311',
    projectId: 'b2b-sales-master-app',
    storageBucket: 'b2b-sales-master-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSRMHbP2yyjwo0cZ9oso5fpKg41kWAo8o',
    appId: '1:703227333311:ios:a8324bbee3e16233e7940a',
    messagingSenderId: '703227333311',
    projectId: 'b2b-sales-master-app',
    storageBucket: 'b2b-sales-master-app.firebasestorage.app',
    iosBundleId: 'com.djezzy.salesMasterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSRMHbP2yyjwo0cZ9oso5fpKg41kWAo8o',
    appId: '1:703227333311:ios:b426fdd1e0d1248ce7940a',
    messagingSenderId: '703227333311',
    projectId: 'b2b-sales-master-app',
    storageBucket: 'b2b-sales-master-app.firebasestorage.app',
    iosBundleId: 'com.example.salesMasterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlHl9933p34pfhLaa-sfUVCTjxDnQwMvk',
    appId: '1:703227333311:web:d99be916b5caf892e7940a',
    messagingSenderId: '703227333311',
    projectId: 'b2b-sales-master-app',
    authDomain: 'b2b-sales-master-app.firebaseapp.com',
    storageBucket: 'b2b-sales-master-app.firebasestorage.app',
    measurementId: 'G-YXV0KY4KH8',
  );

}