Map<String, String> englishDict = {
  "ADDRESS": "Address",
  "All deals": "All deals",
  "DATE": "Date",
  "Date de visite": "Visit date",
  "Date prochaine visite": "Next visit date",
  "Derniers Deals": "Latest deals",
  "INFORMATIONS GÉNÉRALES": "General information",
  "Interlocuteur": "Contact person",
  "Mon Catalogue": "My catalog",
  "My To do list": "My to-do list",
  "Nos Offres": "Our offers",
  "Nos Procedures / Formulaires": "Our procedures / forms",
  "Numero*": "Number*",
  "Ouups. Error Detected!": "Oops. Error detected!",
  "Please check your internet connection and try again":
      "Please check your internet connection and try again",
  "RAPPEL": "Reminder",
  "Raison Sociale*": "Company name*",
  "Refresh": "Refresh",
  "and": "and",
  "badDebt": "Bad debt",
  "bills_data": "Bills data",
  "by_clicking": "By clicking continue, you agree to our ",
  "call": "Call",
  "clients": "Clients",
  "code_sent": "Code sent",
  "could not load pipeline": "Could not load pipeline",
  "failed to load deals": "Failed to load deals",
  "lignes": "Lines",
  "login_description": "it should be your work phone number",
  "login_hint": "Phone Number",
  "login_page_hint": "Phone Number",
  "login_titler": "Enter your Number",
  "mom": "Mom",
  "mon_portfeuille": "My portfolio",
  "my_baddebt": "My bad debt",
  "new_notifications": "New notifications",
  "next": "Next",
  "notifications_page_title": "Notifications",
  "number": "Number",
  "offres": "Offers",
  "older": "Older",
  "otp_title": "OTP title",
  "privacy_policy": " Privacy policy ",
  "prodil_client": "Client profile",
  "read_notifications": "Read notifications",
  "receiving_issue": "Receiving issue",
  "resend_code": "Resend code",
  "terms_of_service": " Terms of service ",
  "today": "Today",
  "Log out": "Log out",
  "There is currently no data in this section":
      "There is currently no data in this section",
  "You have no reminders fors this time period":
      "You have no reminders fors this time period",
  "No reminders": "No reminders",
  "Home": "Home",
  "Clients": "Clients",
  "Pipeline": "Pipeline",
  "Todo": "Todo",
  "Realisations Dashboard": "Realisations Dashboard",
  "Offers": "Offers",
  "No Data": "No Data",
};
