Map<String, String> englishDict = {
  "ADDRESS": "Address",
  "All deals": "All deals",
  "DATE": "Date",
  "Date de visite": "Visit date",
  "Date prochaine visite": "Next visit date",
  "Derniers Deals": "Latest deals",
  "INFORMATIONS GÉNÉRALES": "General information",
  "Interlocuteur": "Contact person",
  "Mon Catalogue": "My catalog",
  "My To do list": "My to-do list",
  "Nos Offres": "Our offers",
  "Nos Procedures / Formulaires": "Our procedures / forms",
  "Numero*": "Number*",
  "Ouups. Error Detected!": "Oops. Error detected!",
  "Please check your internet connection and try again":
      "Please check your internet connection and try again",
  "RAPPEL": "Reminder",
  "Raison Sociale*": "Company name*",
  "Refresh": "Refresh",
  "and": "and",
  "badDebt": "Bad debt",
  "bills_data": "Bills data",
  "by_clicking": "By clicking continue, you agree to our ",
  "call": "Call",
  "clients": "Clients",
  "code_sent": "we’ve sent a code to",
  "could not load pipeline": "Could not load pipeline",
  "failed to load deals": "Failed to load deals",
  "lignes": "Lines",
  "login_description": "it should be your work phone number",
  "login_hint": "Phone Number",
  "login_page_hint": "Phone Number",
  "login_titler": "Enter your Number",
  "mom": "Mom",
  "mon_portfeuille": "My portfolio",
  "my_baddebt": "My bad debt",
  "new_notifications": "New notifications",
  "next": "Next",
  "notifications_page_title": "Notifications",
  "number": "Number",
  "offres": "Offers",
  "older": "Older",
  "otp_title": "Enter verification OTP",
  "privacy_policy": " Privacy policy ",
  "prodil_client": "Client profile",
  "read_notifications": "Read notifications not seen",
    "download":"Download",
    "besoin_detect":"Identified need *",
    "addDeal":"Add New Deal",
     "numberRequired":"Please enter a number",
"operatorRequired":"Please enter the current operator",
"raRequired":"Please enter RA Estimé",
"forfaitRequired":"Please enter current forfait",
 "momRequired":"Please enter MOM",

    "processFormulaires":"Processes & Forms",
    "searchFileName":"Search by file name",
    "procedures":"Procedures",
    "formulaires":"Forms",
    "acunFichier":"No files available",
    "acunFichierDesc":"There are no files for this category at the moment",
    "realisationsTrimestrielles":"Quarterly Performance",
    "selectDestination":"Select the destination",
    "selectDestinationDesc":"Please select a country to display roaming details",
    "callAlgeria":"Call to Algeria",
    "callLocal":"Local Call",
    "callMonde":"Call to the rest of the world",
    "callRecu":"Received Call",
"SMSEmis":"Sent SMS",
"toDoList":"To-Do List",
"searchTaskName":"Search by task name",
"addNew":"Add New",
"editTask":"Edit Task",
"addTask":"Add a Task",
 "language":"Language",

    "search_deals":"Search by Company Name/MSISDN",
    "realisation_total":"My Total Performance",
    "dealTotal":"My Total Deals",
    "HomePage":"Home Page",
    "noReminders":"No reminders",
    "noRemindersDesc":"You have no reminders for this time period",
    "updateDeal":"Edit Deal",
    "mon_pipeline":"My Pipeline",
    "miseajourpipeline":"The deal will be added or updated in your pipeline.",
    "Enregistrer":"Save",
    "successDeal":"The deal has been added.",
    "successUpdateMail":"The Telecom Manager form has been sent by email",
    "catalogue_offre":"Offer Catalogs",
  "receiving_issue": "Receiving issue",
  "resend_code": "Resend code",
  "terms_of_service": " Terms of service ",
  "today": "Today",
  "Log out": "Log out",
  "There is currently no data in this section":
      "There is currently no data in this section",
  "You have no reminders fors this time period":
      "You have no reminders fors this time period",
  "No reminders": "No reminders",
  "Home": "Home",
  "Clients": "Clients",
  "Pipeline": "Pipeline",
  "Todo": "Todo",
  "Realisations Dashboard": "Realisations Dashboard",
  "Offers": "Offers & Services",
  "No Data": "No Data",
    "AffichageAll":"Show all",
"momSuccess":"The MOM has been successfully saved and sent by email.",
"requiredFill":"Please fill in all required fields",

};
