Map<String, String> frenchDict = {
  "ADDRESS": "Adresse",
  "All deals": "Toutes les offres",
  "DATE": "Date",
  "Date de visite": "Date de visite",
  "Date prochaine visite": "Prochaine date de visite",
  "Derniers Deals": "Dernières offres",
  "INFORMATIONS GÉNÉRALES": "Informations générales",
  "Interlocuteur": "Interlocuteur",
  "Mon Catalogue": "Mon catalogue",
  "My To do list": "Ma liste de tâches",
  "Nos Offres": "Nos offres",
  "Nos Procedures / Formulaires": "Nos procédures / formulaires",
  "Numero*": "Numéro*",
  "Ouups. Error Detected!": "Oups. Erreur détectée !",
  "Please check your internet connection and try again":
      "Veuillez vérifier votre connexion Internet et réessayer",
  "RAPPEL": "Rappel",
  "Raison Sociale*": "Raison sociale*",
  "Refresh": "Rafraîchir",
  "and": "et",
  "badDebt": "badDebt",
  "bills_data": "Données de factures",
  "by_clicking": "En cliquant sur Continuer, vous acceptez nos",
  "call": "Appeler",
  "clients": "Clients",
  "code_sent": "Code envoyé",
  "could not load pipeline": "Impossible de charger le pipeline",
  "failed to load deals": "Échec du chargement des offres",
  "lignes": "Lignes",
  "login_description": "Ce doit être votre numéro de téléphone professionnel",
  "login_hint": "Numéro de téléphone",
  "login_page_hint": "Numéro de téléphone",
  "login_titler": "Entrez votre numéro",
  "mom": "Mom",
  "mon_portfeuille": "Mon portefeuille",
  "my_baddebt": "Mes baddebt",
  "new_notifications": "Nouvelles notifications",
  "next": "Suivant",
  "notifications_page_title": "Notifications",
  "number": "Numéro",
  "offres": "Offres",
  "older": "Plus ancien",
  "otp_title": "Titre OTP",
  "privacy_policy": " Politique de confidentialité ",
  "prodil_client": "Profil client",
  "read_notifications": "Notifications lues",
  "receiving_issue": "Problème de réception",
  "resend_code": "Renvoyer le code",
  "terms_of_service": " Conditions d’utilisation ",
  "today": "Aujourd’hui",
  "Log out": "se deconnecter"
};
