Map<String, String> frenchDict = {
  "ADDRESS": "Adresse",
  "All deals": "Toutes les offres",
  "DATE": "Date",
  "Date de visite": "Date de visite",
  "Date prochaine visite": "Prochaine date de visite",
  "Derniers Deals": "Dernières offres",
  "INFORMATIONS GÉNÉRALES": "Informations générales",
  "Interlocuteur": "Interlocuteur",
  "Mon Catalogue": "Mon catalogue",
  "My To do list": "Ma liste de tâches",
  "Nos Offres": "Nos offres",
  "Nos Procedures / Formulaires": "Nos procédures / formulaires",
  "Numero*": "Numéro*",
  "Ouups. Error Detected!": "Oups. Erreur détectée !",
  "Please check your internet connection and try again":
      "Veuillez vérifier votre connexion Internet et réessayer",
  "RAPPEL": "Rappel",
  "Raison Sociale*": "Raison sociale*",
  "Refresh": "Rafraîchir",
  "and": "et",
  "badDebt": "Créances douteuses",
  "bills_data": "Données de factures",
  "by_clicking": "En cliquant",
  "call": "Appeler",
  "clients": "Clients",
  "code_sent": "Code envoyé",
  "could not load pipeline": "Impossible de charger le pipeline",
  "failed to load deals": "Échec du chargement des offres",
  "lignes": "Lignes",
  "login_description": "Description de connexion",
  "login_hint": "Indice de connexion",
  "login_page_hint": "Indice de la page de connexion",
  "login_titler": "Titre de connexion",
  "mom": "Maman",
  "mon_portfeuille": "Mon portefeuille",
  "my_baddebt": "Mes créances douteuses",
  "new_notifications": "Nouvelles notifications",
  "next": "Suivant",
  "notifications_page_title": "Titre de la page de notifications",
  "number": "Numéro",
  "offres": "Offres",
  "older": "Plus ancien",
  "otp_title": "Titre OTP",
  "privacy_policy": "Politique de confidentialité",
  "prodil_client": "Profil client",
  "read_notifications": "Notifications lues",
  "receiving_issue": "Problème de réception",
  "resend_code": "Renvoyer le code",
  "terms_of_service": "Conditions d’utilisation",
  "today": "Aujourd’hui",
};
