Map<String, String> frenchDict = {
  "ADDRESS": "Adresse",
  "All deals": "Toutes les Deal",
  "DATE": "Date",
  "Date de visite": "Date de visite",
  "Date prochaine visite": "Prochaine date de visite",
  "Derniers Deals": "Dernières offres",
  "INFORMATIONS GÉNÉRALES": "Informations générales",
  "Interlocuteur": "Interlocuteur",
  "Mon Catalogue": "Mon catalogue",
  "My To do list": "Ma liste de tâches",
  "Nos Offres": "Nos offres",
  "Nos Procedures / Formulaires": "Nos procédures / formulaires",
  "Numero*": "Numéro*",
  "Ouups. Error Detected!": "Oups. Erreur détectée !",
  "Please check your internet connection and try again":
      "Veuillez vérifier votre connexion Internet et réessayer",
  "RAPPEL": "Rappel",
  "Raison Sociale*": "Raison sociale*",
  "Refresh": "Rafraîchir",
  "and": "et",
  "badDebt": "badDebt",
  "bills_data": "Données de factures",
  "by_clicking": "En cliquant sur Continuer, vous acceptez nos",
  "call": "Appeler",
  "download":"Télécharger",
      "catalogue_offre":"Catalogues d’offres",
    "successUpdateMail":"Le formulaire Télécom Manager a été envoyé par e-mail",
    "Enregistrer":"Enregistrer",
    "successDeal":"Le deal a été ajouté.",
    "miseajourpipeline":"Le deal sera ajouté ou mis à jour sur votre pipeline.",
    "besoin_detect":"Besoin détecté *",
    "addDeal":"Ajouter un deal",
    "updateDeal":"Modifier Deal",
    "mon_pipeline":"Mon pipeline",
    "search_deals":"Rechercher par Raison sociale/MSISDN",
    "realisation_total":"Mes réalisations totales",
    "dealTotal":"Mes deals totaux",
    "HomePage":"Page d’accueil",
    "noReminders":"Aucun rappel",
    "noRemindersDesc":"Vous n’avez aucun rappel pour cette période",
    "processFormulaires":"Processus & Formulaires",
    "searchFileName":"Rechercher par nom de fichier",
    "procedures":"Procédures",
    "formulaires":"Formulaires",
    "acunFichier":"Aucun fichier disponible",
    "acunFichierDesc":"Il n’y a pas de fichier pour cette catégorie pour le moment",
    "realisationsTrimestrielles":"Réalisations Trimestrielles",
    "selectDestination":"Sélectionnez la destination",
    "selectDestinationDesc":"Veuillez sélectionner un pays afin d’afficher les détails du roaming",
    "callAlgeria":"Appel vers l'Algérie",
    "callLocal":"Appel en local",
    "callMonde":"Appel vers le reste du monde",
"callRecu":"Appel reçu",
"SMSEmis":"SMS émis",
"toDoList":"Liste de tâches",
 "searchTaskName":"Rechercher par nom de tâche",
 "language":"Langue",
"addNew":"Ajouter Nouvelle",
"editTask":"Modifier la tâche",
"addTask":"Ajouter une tâche",
  "clients": "Clients",
  "code_sent": "Nous avons envoyé un code à",
  "could not load pipeline": "Impossible de charger le pipeline",
  "failed to load deals": "Échec du chargement des offres",
  "lignes": "Lignes",
  "login_description": "Ce doit être votre numéro de téléphone professionnel",
  "login_hint": "Numéro de téléphone",
  "login_page_hint": "Numéro de téléphone",
  "login_titler": "Entrez votre numéro",
  "mom": "Mom",
  "mon_portfeuille": "Mon portefeuille",
  "my_baddebt": "Mes baddebt",
  "new_notifications": "Nouvelles notifications",
  "next": "Suivant",
  "notifications_page_title": "Notifications",
  "number": "Numéro",
  "offres": "Offres",
  "older": "Plus ancien",
  "otp_title": "Saisissez le code de vérification",
  "privacy_policy": " Politique de confidentialité ",
  "prodil_client": "Profil client",
  "read_notifications": "Notifications Non lues",
  "receiving_issue": "Problème de réception",
  "resend_code": "Renvoyer le code",
  "terms_of_service": " Conditions d’utilisation ",
  "today": "Aujourd’hui",
  "Log out": "se deconnecter",
  "There is currently no data in this section":
      "Il n’y a actuellement aucune donnée dans cette section",
  "You have no reminders fors this time period":
      "Vous n’avez aucun rappel pour cette période",
  "No reminders": "Aucun rappel",
  "Home": "Accueil",
  "Clients": "Clients",
  "Pipeline": "Pipeline",
  "Todo": "Tâches",
  "Realisations Dashboard": "Réalisations",
  "Offers": "Offres & Services",
  "No Data": "Aucune donnée",
  "AffichageAll":"Afficher tous",
"momSuccess":"Le MOM a été correctement enregistré et envoyé par e-mail.",
"requiredFill":"Veuillez remplir tous les champs obligatoires",
"operatorRequired":"Veuillez saisir l’opérateur actuel",
 "numberRequired":"Veuillez entrer un nombre",
 "reRequired":"Veuillez saisir le RA estimé",
 "forfaitRequired":"Veuillez saisir le forfait actuel",
 "momRequired":"Veuillez saisir le MOM",
};
